# Generated by Django 5.2.4 on 2025-07-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfee',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
