# Generated by Django 5.2.4 on 2025-07-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_remove_studentfee_paid_at_payment_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
