# Generated by Django 5.2.4 on 2025-07-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_initial'),
        ('classrooms', '0004_alter_classroom_unique_together'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='class_name',
            new_name='classroom',
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'classroom', 'date')},
        ),
    ]
