# Generated by Django 5.2.4 on 2025-07-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classroom_class_teacher'),
        ('schools', '0003_alter_school_options_school_created_school_modified'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'class_name', 'section', 'class_teacher')},
        ),
    ]
