# Generated by Django 5.2.4 on 2025-07-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_alter_classroom_unique_together'),
        ('schools', '0004_alter_school_options_alter_school_unique_together'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'class_name', 'section', 'class_teacher')},
        ),
    ]
