# Generated by Django 5.2.4 on 2025-07-24 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_alter_classroom_unique_together'),
        ('schools', '0004_alter_school_options_alter_school_unique_together'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'class_name', 'section')},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms_as_teacher', to='teachers.teacher'),
        ),
    ]
