# Generated by Django 5.2.4 on 2025-07-30 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0006_alter_classroom_unique_together_and_more'),
        ('students', '0001_initial'),
        ('subjects', '0006_alter_subject_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('classrooms', models.ManyToManyField(related_name='exams', to='classrooms.classroom')),
            ],
            options={
                'unique_together': {('title',)},
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_schedules', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'unique_together': {('exam', 'subject', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examsubject')),
            ],
            options={
                'unique_together': {('student', 'exam_subject')},
            },
        ),
    ]
