# Generated by Django 5.2.4 on 2025-08-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
