# Generated by Django 5.2.4 on 2025-07-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalReportCard',
        ),
    ]
