# Generated by Django 5.2.4 on 2025-07-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_delete_finalreportcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='weightage',
        ),
    ]
