# Generated by Django 5.2.4 on 2025-07-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='est_year',
            new_name='established_year',
        ),
    ]
