# Generated by Django 5.2.4 on 2025-07-16 10:21

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_est_year_school_established_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='school',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
