# Generated by Django 5.2.4 on 2025-07-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_options_school_created_school_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'address')},
        ),
    ]
