# Generated by Django 5.2.4 on 2025-07-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassroomSubject',
        ),
    ]
