# Generated by Django 5.2.4 on 2025-07-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_subject_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name',)},
        ),
    ]
