# Generated by Django 5.2.4 on 2025-07-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_options_alter_school_unique_together'),
        ('subjects', '0005_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'name')},
        ),
    ]
